#!/usr/bin/env ruby

pdf_name = ARGV[0]

`src2html.pl --tab-width 4 --color --cross-reference --navigator --line-numbers . #{pdf_name}`

`ebook-convert html_out/index.html #{pdf_name}.pdf \
    --override-profile-size \
    --paper-size a4 \
    --pdf-default-font-size 12 \
    --pdf-mono-font-size 12 \
    --margin-left 10 --margin-right 10 \
    --margin-top 10 --margin-bottom 10 \
    --page-breaks-before='/'`
