#!/usr/bin/env ruby

require 'thor'

class SwitchDNS < Thor

  DNS_SERVER_114 = '114.114.114.114'
  DNS_SERVER_DHCP = 'empty'

  CHANGE_DNS_CMMAND = 'networksetup -setdnsservers Wi-Fi '

  desc 'default', 'The default task to run when no command is given'
  def default()
    current_setting = `networksetup -getdnsservers Wi-Fi`.chomp
    if current_setting != DNS_SERVER_114
      cmd = CHANGE_DNS_CMMAND + DNS_SERVER_114
    else
      cmd = CHANGE_DNS_CMMAND + DNS_SERVER_DHCP
    end

    puts "current dns setting: #{dns_description(current_setting)}, changed to #{current_setting == DNS_SERVER_114 ? DNS_SERVER_DHCP : DNS_SERVER_114}"

   `#{cmd}`

  end

  default_task :default

  private

    def dns_description(setting)
      if setting == "There aren't any DNS Servers set on Wi-Fi."
        return 'DHCP'
      end
      return setting
    end
end

SwitchDNS.start( ARGV )
